// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAarcCA5wf2GE124oGKdsEuKEEUxtjYDvw',
    appId: '1:122727763256:web:d378d5e6a8669e654b45cd',
    messagingSenderId: '122727763256',
    projectId: 'saranstore1924',
    authDomain: 'saranstore1924.firebaseapp.com',
    storageBucket: 'saranstore1924.firebasestorage.app',
    measurementId: 'G-CK902DXB2B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApv1fwOwFOAlrLWDGgKu_eVDzm9SsO0xg',
    appId: '1:122727763256:android:3d042bbe004ca35c4b45cd',
    messagingSenderId: '122727763256',
    projectId: 'saranstore1924',
    storageBucket: 'saranstore1924.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-K_fUWIf_2AW-ZgJ_jwYzXdSF9OjrN0E',
    appId: '1:122727763256:ios:d6935ebc3ab430f14b45cd',
    messagingSenderId: '122727763256',
    projectId: 'saranstore1924',
    storageBucket: 'saranstore1924.firebasestorage.app',
    iosBundleId: 'com.example.saranstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-K_fUWIf_2AW-ZgJ_jwYzXdSF9OjrN0E',
    appId: '1:122727763256:ios:d6935ebc3ab430f14b45cd',
    messagingSenderId: '122727763256',
    projectId: 'saranstore1924',
    storageBucket: 'saranstore1924.firebasestorage.app',
    iosBundleId: 'com.example.saranstore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAarcCA5wf2GE124oGKdsEuKEEUxtjYDvw',
    appId: '1:122727763256:web:dd462fadb3c9547c4b45cd',
    messagingSenderId: '122727763256',
    projectId: 'saranstore1924',
    authDomain: 'saranstore1924.firebaseapp.com',
    storageBucket: 'saranstore1924.firebasestorage.app',
    measurementId: 'G-CKRHZV17HL',
  );
}
